In [25]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer

In [26]:
df = pd.DataFrame({
    'rollNo' : [1, 2, 3, None, 5, None, 7, None, 9, 10],
    'Name' : ['Harsh', 'Idris', 'Raza', 'Vardhan', 'Santosh', 'Kumar', None, 'Shashi', 'Manjuth', None],
    'marks' : [35, 50, None, 89, 90, 99, None, 100, None, None ],
    'Grade' : ['C', 'B', np.nan, 'A', 'A+', 'A+', np.nan, 'A+', np.nan, np.nan ]

})

In [27]:
df

,rollNo,Name,marks,Grade
0,1.0,Harsh,35.0,C
1,2.0,Idris,50.0,B
2,3.0,Raza,NaN,NaN
3,NaN,Vardhan,89.0,A
4,5.0,Santosh,90.0,A+
5,NaN,Kumar,99.0,A+
6,7.0,None,NaN,NaN
7,NaN,Shashi,100.0,A+
8,9.0,Manjuth,NaN,NaN
9,10.0,None,NaN,NaN


In [28]:
imputer = SimpleImputer(strategy='constant', fill_value='unknown')
imputer.fit_transform(df[['Name', 'Grade']])

array([['Harsh', 'C'],
       ['Idris', 'B'],
       ['Raza', 'unknown'],
       ['Vardhan', 'A'],
       ['Santosh', 'A+'],
       ['Kumar', 'A+'],
       [None, 'unknown'],
       ['Shashi', 'A+'],
       ['Manjuth', 'unknown'],
       [None, 'unknown']], dtype=object)

In [29]:
imputer = SimpleImputer(strategy='mean')
imputer.fit_transform(df[['rollNo', 'marks']])

array([[  1.        ,  35.        ],
       [  2.        ,  50.        ],
       [  3.        ,  77.16666667],
       [  5.28571429,  89.        ],
       [  5.        ,  90.        ],
       [  5.28571429,  99.        ],
       [  7.        ,  77.16666667],
       [  5.28571429, 100.        ],
       [  9.        ,  77.16666667],
       [ 10.        ,  77.16666667]])

In [30]:
imputer = SimpleImputer(strategy='median')
imputer.fit_transform(df[['rollNo', 'marks']])

array([[  1. ,  35. ],
       [  2. ,  50. ],
       [  3. ,  89.5],
       [  5. ,  89. ],
       [  5. ,  90. ],
       [  5. ,  99. ],
       [  7. ,  89.5],
       [  5. , 100. ],
       [  9. ,  89.5],
       [ 10. ,  89.5]])

In [31]:
imputer = SimpleImputer(strategy='constant', fill_value=0)
imputer.fit_transform(df[['rollNo', 'marks']])

array([[  1.,  35.],
       [  2.,  50.],
       [  3.,   0.],
       [  0.,  89.],
       [  5.,  90.],
       [  0.,  99.],
       [  7.,   0.],
       [  0., 100.],
       [  9.,   0.],
       [ 10.,   0.]])

In [32]:
imputer = SimpleImputer(strategy='constant', fill_value='unknown')
imputer.fit_transform(df[['Name', 'Grade']])

array([['Harsh', 'C'],
       ['Idris', 'B'],
       ['Raza', 'unknown'],
       ['Vardhan', 'A'],
       ['Santosh', 'A+'],
       ['Kumar', 'A+'],
       [None, 'unknown'],
       ['Shashi', 'A+'],
       ['Manjuth', 'unknown'],
       [None, 'unknown']], dtype=object)